CREATE DATABASE QUANLYNH
GO
USE QUANLYNH

SET FORMAT DMY

CREATE TABLE KHACHHANG (
    MAKH CHAR(5) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    DIACHI NVARCHAR(100),
    SODT CHAR(10),
    NGAYSINH SMALLDATETIME,
    CMND CHAR(12)
);

CREATE TABLE LOAITK (
	MALTK CHAR(5) PRIMARY KEY,
	TENLTK NVARCHAR(50),
	MOTA NVARCHAR(100)
);

CREATE TABLE TAIKHOAN (
	SOTK CHAR(10) PRIMARY KEY,
    MAKH CHAR(5) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
    MALTK CHAR(5) FOREIGN KEY REFERENCES LOAITK(MALTK),
    NGAYMO SMALLDATETIME,
    SODU MONEY,
    LAISUAT FLOAT,
    TRANGTHAI BIT
);

CREATE TABLE LOAIGIAODICH (
	MALGD CHAR(5) PRIMARY KEY,
	TENLGD NVARCHAR(50),
	MOTA NVARCHAR(100)
);

CREATE TABLE GIAODICH (
	MAGD CHAR(10) PRIMARY KEY,
	SOTK CHAR(10) FOREIGN KEY REFERENCES TAIKHOAN(SOTK),
	MALGD CHAR(5) FOREIGN KEY REFERENCES LOAIGIAODICH(MALGD),
	NGAYGD SMALLDATETIME,
	SOTIEN MONEY,
	NOIDUNG NVARCHAR(100)
);

-- Hiển thị thông tin các tài khoản của các khách hàng (SoTK, TrangThai, SoDu) đã
-- mở tài khoản vào ngày ‘01/01/2017’ (NgayMo) và sắp xếp kết quả theo số dư tăng dần.

SELECT SOTK, TRANGTHAI, SODU 
FROM TAIKHOAN 
WHERE NGAYMO = '01/01/2017'
ORDER BY SODU ASC

-- Liệt kê mã loại giao dịch (MaLGD) cùng với tổng số tiền (SoTien) giao dịch của
-- từng loại giao dịch.

SELECT MALGD, SUM(SOTIEN) AS TONGSOTIEN
FROM GIAODICH
GROUP BY MALGD

-- Cho biết những khách hàng (MaKH, HoTen, CMND) đã mở cả hai loại tài khoản:
-- tiết kiệm (TenLTK= ‘Tiết kiệm’) và thanh toán (TenLTK= ‘Thanh toán’).

SELECT KH.MAKH, KH.HOTEN, KH.CMND
FROM KHACHHANG KH
WHERE EXISTS (
    SELECT 1
    FROM TAIKHOAN TK
    JOIN LOAITK LTK ON TK.MALTK = LTK.MALTK
    WHERE TK.MAKH = KH.MAKH AND LTK.TENLTK = 'Tiết kiệm'
)
AND EXISTS (
    SELECT 1
    FROM TAIKHOAN TK
    JOIN LOAITK LTK ON TK.MALTK = LTK.MALTK
    WHERE TK.MAKH = KH.MAKH AND LTK.TENLTK = 'Thanh toán'
)

-- Liệt kê thông tin các giao dịch (MaGD, SoTK, MaLGD, NgayGD, SoTien,
-- NoiDung) có số tiền lớn nhất trong tháng 12 năm 2017.

SELECT MAGD, SOTK, MALGD, NGAYGD, SOTIEN, NOIDUNG
FROM GIAODICH
WHERE NGAYGD BETWEEN '2017-12-01' AND '2017-12-31'
AND SOTIEN = (
    SELECT MAX(SOTIEN)
    FROM GIAODICH
    WHERE NGAYGD BETWEEN '2017-12-01' AND '2017-12-31'
)

-- Liệt kê danh sách các khách hàng (MaKH, HoTen, SoDT) đã mở tất cả các loại
-- tài khoản.

SELECT KH.MAKH, KH.HOTEN, KH.SODT
FROM KHACHHANG KH
WHERE NOT EXISTS (
    SELECT 1
    FROM LOAITK LTK
    WHERE NOT EXISTS (
        SELECT 1
        FROM TAIKHOAN TK
        WHERE TK.MAKH = KH.MAKH AND TK.MALTK = LTK.MALTK
    )
)

-- Liệt kê những loại tài khoản (MaLTK, TenLTK) được mở nhiều nhất trong năm
-- 2016.

SELECT MALTK, TENLTK
FROM LOAITK
WHERE MALTK = (
	SELECT TOP 1 MALTK
	FROM TAIKHOAN
	WHERE YEAR(NGAYMO) = 2016
	GROUP BY MALTK
	ORDER BY COUNT(MALTK) DESC
)