CREATE DATABASE QUANLYBANHANG

GO 
USE QUANLYBANHANG

SET FORMAT DMY

CREATE TABLE MATHANG (
	MAMH CHAR(5) PRIMARY KEY,
	TENMH NVARCHAR(50),
	DVT NVARCHAR(20),
	NUOCSX NVARCHAR(20)
);

CREATE TABLE NHACC (
	MACC CHAR(5) PRIMARY KEY,
	TENCC NVARCHAR(50),
	DIACHICC NVARCHAR(100)
);

CREATE TABLE CUNGCAP (
	MACC CHAR(5) FOREIGN KEY REFERENCES NHACC(MACC),
	MAMH CHAR(5) FOREIGN KEY REFERENCES MATHANG(MAMH),
	TUNGAY SMALLDATETIME
);

CREATE TABLE DONDH (
	MADH CHAR(5) PRIMARY KEY,
	NGAYDH SMALLDATETIME,
	MACC CHAR(5) FOREIGN KEY REFERENCES NHACC(MACC),
	TONGTRIGIA MONEY,
	SOMH INT
);

CREATE TABLE CHITIET (
	MADH CHAR(5) FOREIGN KEY REFERENCES DONDH(MADH),
	MAMH CHAR(5) FOREIGN KEY REFERENCES MATHANG(MAMH),
	SOLUONG INT,
	DONGIA MONEY,
	TRIGIA MONEY
);

DECLARE @TRIGIA MONEY = SOLUONG * DONGIA

-- Liệt kê danh sách các đơn hàng (MADH, NGAYDH, TONGTRIGIA) của tên nhà cung
-- cấp ‘Vinamilk’ có tổng trị giá lớn hơn 1.000.000 đồng.

SELECT DH.MADH, DH.NGAYDH, DH.TONGTRIGIA
FROM DONDH DH
JOIN NHACC NCC ON DH.MACC = NCC.MACC
WHERE NCC.TENCC = 'Vinamilk' AND DH.TONGTRIGIA > 1000000

-- Tính tổng số lượng sản phẩm có mã mặt hàng (MAMH) là ‘MH001’ đã đặt hàng trong
-- năm 2018.

SELECT SUM(CT.SOLUONG) AS TONGSOLUONG
FROM CHITIET CT
JOIN DONDH DH ON CT.MADH = DH.MADH
WHERE CT.MAMH = 'MH001' AND YEAR(DH.NGAYDH) = 2018

-- Liệt kê những nhà cung cấp (MACC, TENCC) có thể cung cấp những mặt hàng do ‘Việt
-- Nam’ sản xuất mà không cung cấp những mặt hàng do ‘Trung Quốc’ sản xuất.

SELECT NCC.MACC, NCC.TENCC
FROM NHACC NCC
JOIN CUNGCAP CC ON NCC.MACC = CC.MACC
JOIN MATHANG MH ON CC.MAMH = MH.MAMH
WHERE MH.NUOCSX = 'Việt Nam'
AND NCC.MACC NOT IN (
    SELECT NCC2.MACC
    FROM NHACC NCC2
    JOIN CUNGCAP CC2 ON NCC2.MACC = CC2.MACC
    JOIN MATHANG MH2 ON CC2.MAMH = MH2.MAMH
    WHERE MH2.NUOCSX = 'Trung Quốc'
)
GROUP BY NCC.MACC, NCC.TENCC

-- Tính tổng số mặt hàng (SOMH) của tất cả các đơn đặt hàng theo từng năm. Thông tin hiển
-- thị: Năm đặt hàng, Tổng số mặt hàng.

SELECT YEAR(NGAYDH) AS NAMDAT, SUM(SOMH) AS TONGSOMH
FROM DONDH
GROUP BY YEAR(NGAYDH)
ORDER BY YEAR(NGAYDH)

-- Tìm những mã đơn đặt hàng (MADH) đã đặt tất cả các mặt hàng của nhà cung cấp có tên
-- là ‘Vissan’ (TENCC).

SELECT DH.MADH
FROM DONDH DH
JOIN CHITIET CT ON DH.MADH = CT.MADH
JOIN MATHANG MH ON CT.MAMH = MH.MAMH
JOIN NHACC NCC ON DH.MACC = NCC.MACC
WHERE NCC.TENCC = 'Vissan'
GROUP BY DH.MADH
HAVING COUNT(DISTINCT MH.MAMH) = (
    SELECT COUNT(DISTINCT MH2.MAMH)
    FROM MATHANG MH2
    JOIN CUNGCAP CC ON MH2.MAMH = CC.MAMH
    JOIN NHACC NCC2 ON CC.MACC = NCC2.MACC
    WHERE NCC2.TENCC = 'Vissan'
)

-- Tìm những mặt hàng (MAMH, TENMH) có số lượng đặt hàng nhiều nhất trong năm
-- 2018.

SELECT TOP 1 MH.MAMH, MH.TENMH, SUM(CT.SOLUONG) AS TONGSOLUONG
FROM CHITIET CT
JOIN DONDH DH ON CT.MADH = DH.MADH
JOIN MATHANG MH ON CT.MAMH = MH.MAMH
WHERE YEAR(DH.NGAYDH) = 2018
GROUP BY MH.MAMH, MH.TENMH
ORDER BY TONGSOLUONG DESC;