CREATE DATABASE QUANLYCH

GO 
USE QUANLYCH

CREATE TABLE KHACHHANG (
	MAKH CHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	DIACHI NVARCHAR(100),
	NGAYSINH SMALLDATETIME,
	CMND CHAR(12)
);

CREATE TABLE LOAICH (
	MALCH CHAR(5) PRIMARY KEY,
	TENLCH NVARCHAR(20),
	NHOMCC NVARCHAR(20)
);

CREATE TABLE CANHO (
	MACH CHAR(5) PRIMARY KEY,
	TENCH NVARCHAR(50),
	MALCH CHAR(5) FOREIGN KEY REFERENCES LOAICH(MALCH),
	DIENTICH FLOAT,
	VITRI NVARCHAR(50),
	SOPHONG INT,
	GIA MONEY
);

CREATE TABLE HINHTHUCTG (
    MAHT CHAR(5) PRIMARY KEY,
	TENHT NVARCHAR(50),
	PHANTRAMTT FLOAT,
	LAISUAT FLOAT,
	KYHAN INT
);

CREATE TABLE TRAGOP (
	MATG CHAR(5) PRIMARY KEY,
	MACH CHAR(5) FOREIGN KEY REFERENCES CANHO(MACH),
	MAKH CHAR(5) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	MAHT CHAR(5) FOREIGN KEY REFERENCES HINHTHUCTG(MAHT),
	NGAYMUA SMALLDATETIME,
	SOTIENTT MONEY,
);

-- Tìm thông tin những khách hàng (MAKH, TENKH, DIACHI) có năm sinh từ 1980 đến
-- 1985 đã mua trả góp căn hộ vào ngày ‘1/2/2023’ (NGAYMUA).

SELECT KHACHHANG.MAKH, HOTEN, DIACHI
FROM KHACHHANG, TRAGOP
WHERE KHACHHANG.MAKH = TRAGOP.MAKH AND 
YEAR(NGAYSINH) BETWEEN 1980 AND 1985 
AND NGAYMUA = '1/2/2023'

-- Liệt kê thông tin các khách hàng (TENKH, DIACHI) mua trả góp căn hộ có diện tích trên
-- 80m2. Kết quả xuất ra theo tên khách hàng có thứ tự giảm dần.

SELECT KH.HOTEN, KH.DIACHI
FROM KHACHHANG KH
JOIN TRAGOP TG ON KH.MAKH = TG.MAKH
JOIN CANHO CH ON TG.MACH = CH.MACH
WHERE CH.DIENTICH > 80
ORDER BY KH.HOTEN DESC;

-- Liệt kê mã loại căn hộ (MALCH), tên loại căn hộ (TENLCH) và số lượng căn hộ trong
-- từng loại căn hộ.

SELECT LC.MALCH, LC.TENLCH, COUNT(CH.MACH) AS SOLUONGCANHO
FROM LOAICH LCH
JOIN CANHO CH ON LCH.MALCH = CH.MALCH
GROUP BY LCH.MALCH, LCH.TENLCH;

-- Cho biết khách hàng (MAKH, TENKH) đang trả góp nhóm chung cư (NHOMCC) ‘cao
-- cấp’ nhưng không trả góp nhóm chung cư ‘trung cấp’.

SELECT KH.MAKH, KH.HOTEN
FROM KHACHHANG KH
JOIN TRAGOP TG ON KH.MAKH = TG.MAKH
JOIN CANHO CH ON TG.MACH = CH.MACH
JOIN LOAICH LC ON CH.MALCH = LC.MALCH
WHERE LC.NHOMCC = 'cao cấp'
AND KH.MAKH NOT IN (
    SELECT KH2.MAKH
    FROM KHACHHANG KH2
    JOIN TRAGOP TG2 ON KH2.MAKH = TG2.MAKH
    JOIN CANHO CH2 ON TG2.MACH = CH2.MACH
    JOIN LOAICH LC2 ON CH2.MALCH = LC2.MALCH
    WHERE LC2.NHOMCC = 'trung cấp'
)

-- Tìm khách hàng (TENKH) đã mua trả góp tất cả các căn hộ loại ‘penthouse’ của nhóm
-- chung cư ‘cao cấp’.

SELECT KH.HOTEN
FROM KHACHHANG KH
JOIN TRAGOP TG ON KH.MAKH = TG.MAKH
JOIN CANHO CH ON TG.MACH = CH.MACH
JOIN LOAICH LCH ON CH.MALCH = LC.MALCH
WHERE LCH.TENLCH = 'penthouse' AND LCH.NHOMCC = 'cao cấp'
GROUP BY KH.HOTEN
HAVING COUNT(DISTINCT CH.MACH) = (
    SELECT COUNT(DISTINCT CH2.MACH)
    FROM CANHO CH2
    JOIN LOAICH LCH2 ON CH2.MALCH = LCH2.MALCH
    WHERE LCH2.TENLCH = 'penthouse' AND LCH2.NHOMCC = 'cao cấp'
)

-- Trong năm 2022, loại căn hộ nào (MALCH, TENLCH) thuộc nhóm chung cư 'cao cấp' có
-- số lượt bán trả góp nhiều hơn 10.

SELECT LC.MALCH, LC.TENLCH, COUNT(TG.MATG) AS SOLUOTBAN
FROM LOAICH LCH
JOIN CANHO CH ON LCH.MALCH = CH.MALCH
JOIN TRAGOP TG ON CH.MACH = TG.MACH
WHERE LCH.NHOMCC = 'cao cấp' AND YEAR(TG.NGAYMUA) = 2022
GROUP BY LCH.MALCH, LCH.TENLCH
HAVING COUNT(TG.MATG) > 10