CREATE DATABASE QUANLYNCKH

GO 
USE QUANLYNCKH

CREATE TABLE PHONG (
	MAPHONG CHAR(5) PRIMARY KEY,
	TENPHONG NVARCHAR(50),
	NHIEMVU NVARCHAR(100),
	MATRP CHAR(5) FOREIGN KEY REFERENCES NHANVIEN(MANV)
);

CREATE TABLE NHANVIEN (
	MANV CHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	DIACHI NVARCHAR(100),
	EMAIL NVARCHAR(50),
	GIOITINH VARCHAR(3),
	SODT CHAR(10),
	DANTOC NVARCHAR(20),
	MAPHONG CHAR(5) FOREIGN KEY REFERENCES PHONG(MAPHONG)
);

CREATE TABLE DETAI (
	MADT CHAR(5) PRIMARY KEY,
	TENDT NVARCHAR(50),
	TOMTAT NVARCHAR(100),
	LOAIDT NVARCHAR(20),
	KINHPHI MONEY,
	NGAYBD SMALLDATETIME,
	NGAYKT SMALLDATETIME,
	NGHIEMTHU BIT
);

CREATE TABLE THAMGIADT (
	MANV CHAR(5) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	MADT CHAR(5) FOREIGN KEY REFERENCES DETAI(MADT),
	VAITRODT NVARCHAR(50),
	DONGGOPDT FLOAT
);

CREATE TABLE BAIBAOKH (
	MABB CHAR(5) PRIMARY KEY,
	TENBB NVARCHAR(50),
	NHAXB NVARCHAR(50),
	NGAYCN SMALLDATETIME,
	NGAYCB SMALLDATETIME,
	HANG NVARCHAR(2),
	LOAIBB NVARCHAR(20),
	MADT CHAR(5) FOREIGN KEY REFERENCES DETAI(MADT)
);

CREATE TABLE CONGBOBB (
	MANV CHAR(5) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	MABB CHAR(5) FOREIGN KEY REFERENCES BAIBAOKH(MABB),
	VAITROBB NVARCHAR(50),
	DONGGOPBB FLOAT
);

-- Liệt kê nhân viên (MaNV, HoTen) và tên phòng (TenPhong) của phòng có nhiệm vụ là
-- ‘Nghiên cứu’. Sắp xếp kết quả trả về giảm dần theo mã nhân viên.

SELECT NV.MANV, NV.HOTEN, P.TENPHONG
FROM NHANVIEN NV
JOIN PHONG P ON NV.MAPHONG = P.MAPHONG
WHERE P.NHIEMVU = 'Nghiên cứu'
ORDER BY NV.MANV DESC

-- Liệt kê nhân viên (MaNV, HoTen) và loại đề tài (LoaiDT) mà nhân viên đã tham gia trong
-- năm 2023 (NgayBD) với vai trò là ‘chủ nhiệm’ đề tài.

SELECT NV.MANV, NV.HOTEN, DT.LOAIDT
FROM NHANVIEN NV
JOIN THAMGIADT TG ON NV.MANV = TG.MANV
JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE TG.VAITRODT = 'chủ nhiệm'
AND YEAR(DT.NGAYBD) = 2023

-- Cho biết các nhân viên (MaNV, HoTen) đã công bố bài báo khoa học nhưng không phải là
-- ‘tác giả chính’ của bất kỳ bài báo khoa học nào.

SELECT DISTINCT NV.MANV, NV.HOTEN
FROM NHANVIEN NV
JOIN CONGBOBB CB ON NV.MANV = CB.MANV
WHERE NV.MANV NOT IN (
    SELECT MANV
    FROM CONGBOBB
    WHERE VAITROBB = 'tác giả chính'
)

-- Liệt kê mã đề tài, tên đề tài cùng với số lượng bài báo khoa học của các đề tài này được
-- công bố trong năm 2023 (NgayCB).

SELECT DT.MADT, DT.TENDT, COUNT(BB.MABB) AS SOLUONGBB
FROM DETAI DT
JOIN BAIBAOKH BB ON DT.MADT = BB.MADT
WHERE YEAR(BB.NGAYCB) = 2023
GROUP BY DT.MADT, DT.TENDT;

-- Tìm nhân viên (HOTEN) đã công bố tất cả các bài báo khoa học trên ‘tạp chí quốc tế’ của
-- đề tài có mã đề tài ‘DT01’.

SELECT NV.HOTEN
FROM NHANVIEN NV
JOIN CONGBOBB CB ON NV.MANV = CB.MANV
JOIN BAIBAOKH BB ON CB.MABB = BB.MABB
WHERE BB.LOAIBB = 'tạp chí quốc tế'
AND BB.MADT = 'DT01'
GROUP BY NV.HOTEN
HAVING COUNT(BB.MABB) = (
    SELECT COUNT(BB2.MABB)
    FROM BAIBAOKH BB2
    WHERE BB2.LOAIBB = 'tạp chí quốc tế'
    AND BB2.MADT = 'DT01'
)

-- Với mỗi phòng, tìm nhân viên (MaNV, HoTen) tham gia ít đề tài nhất.

WITH DEM_NV AS (
    SELECT NV.MANV, NV.HOTEN, NV.MAPHONG, COUNT(TG.MADT) AS DEM_DETAI
    FROM NHANVIEN NV
    LEFT JOIN THAMGIADT TG ON NV.MANV = TG.MANV
    GROUP BY NV.MANV, NV.HOTEN, NV.MAPHONG
),
IT_DETAI_NHAT AS (
    SELECT MAPHONG, MIN(DEM_DETAI) AS IT_NHAT
    FROM DEM_NV
    GROUP BY MAPHONG
)
SELECT DEM.MANV, DEM.HOTEN, DEM.MAPHONG
FROM DEM_NV DEM
JOIN IT_DETAI_NHAT IT ON DEM.MAPHONG = IT.MAPHONG AND DEM.ProjectCount = IT.MinCount;